### ISSUE TITLE
data

### ISSUE THREAD

**Issue by deepzlk** [Rajesh-ML-Engg/Coronary_Heart_Disease#11]
your project is very interesting and i very need your raw bmp picutres and wish to receieve your help soon, thank you!

**Comment by raj-shr-git** [comment]
@deepzlk , you can download the pics(Heart_pumping1.gif and Heart_pumping2.gif) which I have used from the branch itself.
or download pics from the below links:
[pic1](https://github.com/Rajesh-ML-Engg/Coronary_Artery_Disease/blob/master/Heart_pumping1.gif)
[pic2](https://github.com/Rajesh-ML-Engg/Coronary_Artery_Disease/blob/master/Heart_pumping2.gif)
